---
- name: ifreload
  ansible.builtin.command:
    cmd: ifreload -a
  changed_when: true
  listen: ifreload

- name: update initramfs
  ansible.builtin.command:
    cmd: update-initramfs -u
  changed_when: true
  listen: update initramfs