---
ansible_user: root

pve_cluster_name: pa-cluster
pve_primary_node: pve1.pa.lan
pve_primary_ip: 172.16.255.11

pve_api_user: root@pam
pve_api_port: 8006
pve_validate_certs: false

pve_api_password: "{{ vault_pve_root_password }}"