---
all:
  children:
    firewalls:
      hosts:
        fw-pa-01:
          ansible_host: 172.16.255.20
          ansible_user: root
          ansible_python_interpreter: /usr/local/bin/python3
    dns:
      hosts:
        pdns1:
        pdns2:
    proxmox:
      hosts:
        pve1.pa.lan:
          ansible_host: 172.16.255.11
          pve_node_ip: 172.16.255.11
          pve_node_name: pve1

        pve2.pa.lan:
          ansible_host: 172.16.255.12
          pve_node_ip: 172.16.255.12
          pve_node_name: pve2

        pve3.pa.lan:
          ansible_host: 172.16.255.13
          pve_node_ip: 172.16.255.13
          pve_node_name: pve3
    openbao_hosts:
      hosts:
        openbao:
    docker_hosts:
      hosts:
        authentik:
    traefik_hosts:
      hosts:
        traefik:
    authentik_hosts:
      hosts:
        authentik:
