---
all:
  children:
    proxmox:
      hosts:
        pve1.pa.lan:
          ansible_host: 172.16.255.11
          pve_node_ip: 172.16.255.11
          pve_node_name: pve1

        pve2.pa.lan:
          ansible_host: 172.16.255.12
          pve_node_ip: 172.16.255.12
          pve_node_name: pve2

        pve3.pa.lan:
          ansible_host: 172.16.255.13
          pve_node_ip: 172.16.255.13
          pve_node_name: pve3