---
all:
  children:
    workloads:
      vars:
        ansible_ssh_private_key_file: "~/.ssh/proxmox_iac"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
      children:        bck:
          hosts:            pbs:
              ansible_host: 10.0.50.5
              ansible_user: ansible
              pa_workload_vmid: 150
              pa_workload_kind: vm        srv:
          hosts:            pdns1:
              ansible_host: 10.0.20.5
              ansible_user: root
              pa_workload_vmid: 120
              pa_workload_kind: lxc            pdns2:
              ansible_host: 10.0.20.6
              ansible_user: root
              pa_workload_vmid: 121
              pa_workload_kind: lxc