---
- name: Calculer l'IP corosync de ce nœud
  ansible.builtin.set_fact:
    pve_corosync_ip: "{{ pa_corosync_prefix }}.{{ pve_node_ip.split('.')[-1] }}"

- name: Check current cluster status
  ansible.builtin.command: pvecm status
  register: pvecm_status
  changed_when: false
  failed_when: false

- name: Create Proxmox cluster on primary node
  community.proxmox.proxmox_cluster:
    api_host: "{{ ansible_host }}"
    api_user: "{{ pve_api_user }}"
    api_password: "{{ pve_api_password }}"
    api_port: "{{ pve_api_port }}"
    validate_certs: "{{ pve_validate_certs }}"
    state: present
    cluster_name: "{{ pve_cluster_name }}"
    link0: "{{ pve_corosync_ip }}"
    link1: "{{ pve_node_ip }}"
  delegate_to: localhost
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  no_log: true
  register: pve_cluster_created
  when:
    - inventory_hostname == pve_primary_node
    - "'Name:' not in pvecm_status.stdout"

- name: Wait after cluster creation
  ansible.builtin.pause:
    seconds: 20
  when:
    - inventory_hostname == pve_primary_node
    - pve_cluster_created is changed

- name: Get primary node certificate fingerprint
  ansible.builtin.shell: |
    openssl x509 -in /etc/pve/local/pve-ssl.pem -noout -fingerprint -sha256 | cut -d= -f2 | tr -d '\n'
  delegate_to: "{{ pve_primary_node }}"
  register: pve_primary_fingerprint
  changed_when: false
  when:
    - inventory_hostname != pve_primary_node
    - "'Name:' not in pvecm_status.stdout"

- name: Join node to Proxmox cluster
  community.proxmox.proxmox_cluster:
    api_host: "{{ ansible_host }}"
    api_user: "{{ pve_api_user }}"
    api_password: "{{ pve_api_password }}"
    api_port: "{{ pve_api_port }}"
    validate_certs: "{{ pve_validate_certs }}"
    state: present
    cluster_name: "{{ pve_cluster_name }}"
    master_ip: "{{ pve_primary_ip }}"
    master_api_password: "{{ pve_api_password }}"
    fingerprint: "{{ pve_primary_fingerprint.stdout | trim }}"
    link0: "{{ pve_corosync_ip }}"
    link1: "{{ pve_node_ip }}"
  delegate_to: localhost
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  no_log: true
  throttle: 1
  register: pve_node_joined
  when:
    - inventory_hostname != pve_primary_node
    - "'Name:' not in pvecm_status.stdout"

- name: Wait after node join
  ansible.builtin.pause:
    seconds: 20
  when:
    - inventory_hostname != pve_primary_node
    - pve_node_joined is changed

- name: Display final cluster status
  ansible.builtin.command: pvecm status
  register: final_cluster_status
  changed_when: false
  failed_when: false

- name: Print cluster status
  ansible.builtin.debug:
    var: final_cluster_status.stdout_lines
